# 開発用設定
version: '3'
services:
  web:
    image: node:17.9.0-alpine
    container_name: recipe_app
    volumes:
      - recipe_web:/web
    working_dir: /web
    ports:
      - 3001:3000
    tty: true

  api:
    image: python:3.7
    container_name: recipe_api
    volumes:
      - recipe_server:/server
    working_dir: /server
    ports:
      - 8001:8000
    tty: true

  db:
    image: mysql:8.0
    container_name: recipe_db
    volumes:
      - recipe_db:/db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=Asia/Tokyo
    ports:
      - ${DB_PORT}:3306

volumes:
  recipe_web:
  recipe_server:
  recipe_db:
